instanceID: "$UNIQUE_INSTANCE_IDENTIFIER"
namespace: $APIGEE_NAMESPACE # Usually "apigee"

gcp:
  projectID: $PROJECT_ID
  region: $ANALYTICS_REGION

k8sCluster:
  name: $CLUSTER_NAME
  region: $CLUSTER_LOCATION # Must be the closest Google Cloud region to your cluster.
org: $ORG_NAME

envs:
- name: $ENVIRONMENT_NAME
  serviceAccountPaths:
  # Provide the path relative to the chart directory.
    synchronizer: $NON_PROD_SERVICE_ACCOUNT_FILEPATH
      # For example: "$PROJECT_ID-apigee-non-prod.json"
    runtime: $NON_PROD_SERVICE_ACCOUNT_FILEPATH
      # For example: "$PROJECT_ID-apigee-non-prod.json"
    udca: $NON_PROD_SERVICE_ACCOUNT_FILEPATH
      # For example: "$PROJECT_ID-apigee-non-prod.json"

cassandra:
  hostNetwork: false
    # Set to false for single region installations and multi-region installations
    # with connectivity between pods in different clusters, for example GKE installations.
    # Set to true  for multi-region installations with no communication between
    # pods in different clusters, for example GKE On-prem, GKE on AWS, Anthos on bare metal,
    # AKS, EKS, and OpenShift installations.
    # See Multi-region deployment: Prerequisites
  replicaCount: 1
    # Use 1 for non-prod or "demo" installations and multiples of 3 for production.
    # See Configure Cassandra for production for guidelines.

ingressGateways:
- name: $INGRESS_NAME # maximum 17 characters. See Known issue 243167389.
  replicaCountMin: 2
  replicaCountMax: 10
  svcAnnotations:  # optional. If you are on AKS, see Known issue #260772383
    $SVC_ANNOTATIONS_KEY: $SVC_ANNOTATIONS_VALUE

virtualhosts:
- name: $ENVIRONMENT_GROUP_NAME
  selector:
    app: apigee-ingressgateway
    ingress_name: $INGRESS_NAME
  sslCertPath: $PATH_TO_CERT_FILE
  sslKeyPath: $PATH_TO_KEY_FILE

mart:
  serviceAccountPath: $NON_PROD_SERVICE_ACCOUNT_FILEPATH
  # Provide the path relative to the chart directory.
  # For example: "$PROJECT_ID-apigee-non-prod.json"

connectAgent:
  serviceAccountPath: $NON_PROD_SERVICE_ACCOUNT_FILEPATH
  # Provide the path relative to the chart directory.
  # Use the same service account for mart and connectAgent
    # For example: "$PROJECT_ID-apigee-non-prod.json"

logger:
  enabled: false
        # enabled by default
        # See apigee-logger in Service accounts and roles used by hybrid components.
  serviceAccountPath: $NON_PROD_SERVICE_ACCOUNT_FILEPATH
  # Provide the path relative to the chart directory.
  # For example: "$PROJECT_ID-apigee-non-prod.json"

metrics:
  enabled: false
  serviceAccountPath: $NON_PROD_SERVICE_ACCOUNT_FILEPATH
  # Provide the path relative to the chart directory.
  # For example: "$PROJECT_ID-apigee-non-prod.json"

udca:
  serviceAccountPath: $NON_PROD_SERVICE_ACCOUNT_FILEPATH
  # Provide the path relative to the chart directory.
  # For example: "$PROJECT_ID-apigee-non-prod.json"

watcher:
  serviceAccountPath: $NON_PROD_SERVICE_ACCOUNT_FILEPATH
  # Provide the path relative to the chart directory.
  # For example: "$PROJECT_ID-apigee-non-prod.json"

